class CallError {
  final String code;
  final String description;
  final bool localError; //if error is generated by the app or got from the backend. Backend errors are already in the proper locale

  const CallError({required this.code, required this.description, this.localError = false});

  factory CallError.fromJson(Map<String, dynamic> json) {
    return CallError(
      code: json["Code"],
      description: json["Description"],
    );
  }
}